Fix #1321 - MorphiaLazyModel: Refactor in 14.0.0
primefaces-extensions/primefaces-extensions pull request #1456
Opened 2024-02-27 22:44 UTC by Rapster

2024-02-27 23:29 UTC, newk5 commented
Thanks! Sorry I haven't been able to look into this yet, I'm not familiar with the new LazyDatamodel refactor that was done recently in PF. 

I was now looking through this commit and I agree with all changes except one in particular with the builder. I think we should rename the entityManager(etc..) to datastore(etc..) because morphia has no concept of entity managers, entity managers usually mean JPA related stuff. I understand this probably came from the JPALazyDataModel in PF, and wanting to normalize the API to be the same between the JPALazyModel and MorphiaLazyDataModel but for morphia users, the term "entityManager" will probably cause confusion, since morphia always refers to it as "datastore"

2024-02-27 23:41 UTC, Rapster commented
Yup, just an oversight

2024-02-28 00:02 UTC, melloware requested changes

2024-02-28 00:02 UTC, melloware commented on core/src/main/java/org/primefaces/extensions/model/mongo/MorphiaLazyDataModel.java
> +        public Builder<T> entityManager(SerializableSupplier<Datastore> datastore) {
EntityManager to Datastore and then I think this is great!

2024-02-28 00:22 UTC, melloware approved these changes

2024-02-28 00:22 UTC, merged

2024-02-28 09:25 UTC, Rapster commented
Be aware I couldn't test it (or we have a branch for that?)

2024-02-28 11:25 UTC, melloware commented
We don't. This code was donated by @newk5 as he uses it heavily in his company.