Creates an Open Steet Map Component
primefaces-extensions/primefaces-extensions pull request #1556
Opened 2024-05-26 20:34 UTC by mores

Resolves: 
https://github.com/primefaces/primefaces/issues/40
https://github.com/primefaces/primefaces/issues/3601

Features:
Markers
MarkerDrag
Overlays ( Circle, Polygon, Polyline, Rectangle )
PointSelect
StateChange

2024-05-27 11:51 UTC, melloware requested changes

2024-05-27 11:51 UTC, melloware commented on core/src/main/resources/META-INF/primefaces-extensions.taglib.xml
> +        </component>
It looks like you are missing all the props in the taglib?  ` widgetVar, model, style, styleClass, center, zoom, attribution, tileUrl, draggable` ?

2024-05-27 11:51 UTC, melloware commented on core/src/main/java/org/primefaces/extensions/component/osmap/OSMapRenderer.java
> +        wb.nativeAttr("map", "L.map('" + map.getClientId() + "_map').setView(['" + parts[0].trim() + "', '" + parts[1].trim() + "'], " + map.getZoom() + ")");
I feel like the two URL props should be moved to the widget.js because of the hardcoding of `/jakarta.faces.resource/`  @jepsar i feel like we have a better way to do this?

2024-05-27 11:51 UTC, melloware commented on core/src/main/java/org/primefaces/extensions/component/osmap/OSMapRenderer.java
> +        wb.nativeAttr("map", "L.map('" + map.getClientId() + "_map').setView(['" + parts[0].trim() + "', '" + parts[1].trim() + "'], " + map.getZoom() + ")");
OK found it on the client side you can do this in the widget

```js
this.cfg.iconUrl = PrimeFaces.resources.getFacesResource('leaflet/images/marker-icon.png', PrimeFacesExt.RESOURCE_LIBRARY, PrimeFacesExt.VERSION)
```

2024-05-28 13:11 UTC, mores commented on core/src/main/java/org/primefaces/extensions/component/osmap/OSMapRenderer.java
> +        wb.nativeAttr("map", "L.map('" + map.getClientId() + "_map').setView(['" + parts[0].trim() + "', '" + parts[1].trim() + "'], " + map.getZoom() + ")");
Merge has been updated.

2024-05-28 14:17 UTC, mores commented on core/src/main/resources/META-INF/primefaces-extensions.taglib.xml
> +        </component>
Merge has been updated.

2024-05-28 14:26 UTC, melloware approved these changes

2024-05-28 14:26 UTC, melloware commented
awesome.  I will test this component out and make a showcase example for it for my testing.

2024-05-28 19:40 UTC, merged

2024-09-25 12:06 UTC, mores commented
@melloware  when/how does this get added to the showcase ?

2024-09-25 12:23 UTC, melloware commented
14.0.0 is still deployed let me ask PrimeTek to see if they can deploy 14.0.5