Fix #296 Added LightSwitch
primefaces-extensions/primefaces-extensions pull request #297
Opened 2021-01-30 17:25 UTC by jepsar

Fix #296

Showcase is still to do.. I'll take care of that after this has been reviewed

2021-01-30 17:30 UTC, melloware reviewed
Cool let me check this out!

2021-01-30 19:11 UTC, melloware approved these changes
Looks good to me.

2021-01-30 19:51 UTC, melloware commented
I also just fixed some oddities with our themeswitcher and deleted a bunch of old JS methods for theme switching in core.js that weren't even being used!

2021-01-30 22:19 UTC, jepsar commented on core/src/main/java/org/primefaces/extensions/component/lightswitch/LightSwitchRenderer.java
> +    public static final String ATTR_THEME = "org.primefaces.extensions.component.lightswitch.THEME";
Remove

2021-01-31 15:00 UTC, melloware requested changes
I am thinking one more good change might be a `disabled` flag on the component and two new widget methods for `enable` and `disable`.  This way people can control it if they need to.

2021-01-31 18:14 UTC, jepsar commented
> I am thinking one more good change might be a `disabled` flag on the component and two new widget methods for `enable` and `disable`. This way people can control it if they need to.

I added an `automatic` attribute instead and some API functions to control the switch. Disabling does not make sense to me as it's only executed on page load. If you don't want it to run you can now use `automatic="false"` or `rendered="false"`.

2021-01-31 19:18 UTC, melloware approved these changes
Ok good you are safe to squash and merge it!

2021-01-31 19:19 UTC, merged