Fix #650: added InputPhone
primefaces-extensions/primefaces-extensions pull request #64
Opened 2019-02-26 20:42 UTC by jepsar

2019-02-26 20:45 UTC, melloware requested changes
Don't forget you need to add it to the taglib.xml file too and all its properties.

2019-02-26 20:46 UTC, melloware requested changes

2019-02-26 20:46 UTC, melloware commented on src/main/java/org/primefaces/extensions/component/inputphone/Country.java
> +
Best to make this implement Serializable and add an equals(), toString(), and hashCode(). Whenevre you have these POJO's you never know how someone might use them or put them in SessionScoped beans etc.

2019-02-26 20:50 UTC, jepsar commented
> Don't forget you need to add it to the taglib.xml file too and all its properties.

Sorry, I'm not sure what you mean. I modified primefaces-extensions.taglib.xml. Did I miss something?

2019-02-26 21:00 UTC, tandraschko reviewed
In pf core we would put this class into the model package

2019-02-26 21:02 UTC, jepsar commented
> In pf core we would put this class into the model package

I wasn't sure about this.. I'll move it.

2019-02-26 21:09 UTC, melloware commented
@jepsar Nice work.  For some reason the taglib was now showing up in my Diff but it is now!  Thanks.  I will merge tonight and send you a note when i have it all working with minifying everything correctly.

2019-02-27 00:36 UTC, melloware approved these changes

2019-02-27 00:37 UTC, merged